# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Ruhee Dewji"
description:        "Ruhee Dewji is a musician in Toronto, Ontario."

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
url:                "//ruheedewji.com"
author:             "Ruhee Dewji"
twitter:
  username:         "ruhee_"

# URL
baseurl:            ""
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title/

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "About"
    href:           "/about"
  - name:           "Music"
    href:           "/music"
  - name:           "Shows"
    href:           "/shows"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-seo-tag
